import type { Course } from './types';

// Demo data so the UI works before you connect a real backend.
export const SEMESTERS = [
  { id: '202620', label: 'Spring 2025-2026' },
  { id: '202610', label: 'Fall 2025-2026' },
  { id: '202530', label: 'Summer 2024-2025' },
];

export const COURSES: Course[] = [
  {
    id: 'CMPS271-1',
    crn: '27101',
    code: 'CMPS 271',
    title: 'Software Engineering',
    instructor: 'Dr. Mohamad Z.',
    campus: 'Main Campus',
    section: '1',
    credits: 3,
    capacity: { enrolled: 24, limit: 30 },
    attributes: ['Quantitative Thought'],
    prerequisites: 'CMPS 202',
    restrictions: 'None',
    difficulty: 4.2,
    workload: 4.4,
    meetings: [
      { days: ['T', 'R'], start: '14:00', end: '15:15', location: 'Nicely Hall 401', type: 'Lecture' },
    ],
  },
  {
    id: 'CMPS244-1',
    crn: '24407',
    code: 'CMPS 244',
    title: 'Theory of Computation',
    instructor: 'Dr. A. H.',
    campus: 'Main Campus',
    section: '1',
    credits: 3,
    capacity: { enrolled: 18, limit: 25 },
    attributes: ['Quantitative Thought'],
    prerequisites: 'CMPS 214',
    restrictions: 'None',
    difficulty: 4.6,
    workload: 4.1,
    meetings: [
      { days: ['M', 'W'], start: '12:30', end: '13:45', location: 'Fakih 207', type: 'Lecture' },
    ],
  },
  {
    id: 'EDUC218-1',
    crn: '21802',
    code: 'EDUC 218',
    title: "Children's Literature",
    instructor: 'Dr. Amal BouZeineddine',
    campus: 'Main Campus',
    section: '1',
    credits: 3,
    capacity: { enrolled: 22, limit: 22 },
    attributes: ['Humanities II'],
    prerequisites: 'None',
    restrictions: 'May not be enrolled as: Freshman',
    difficulty: 3.1,
    workload: 3.0,
    meetings: [
      { days: ['M', 'W'], start: '14:00', end: '15:15', location: 'College Hall 203', type: 'Lecture' },
    ],
  },
  {
    id: 'ARAB232-1',
    crn: '23210',
    code: 'ARAB 232',
    title: 'Arabic Communication Skills',
    instructor: 'Samir Malti',
    campus: 'Main Campus',
    section: '1',
    credits: 3,
    capacity: { enrolled: 26, limit: 28 },
    attributes: ['Arabic Communication Skills'],
    prerequisites: 'ARAB 201',
    restrictions: 'None',
    difficulty: 3.7,
    workload: 3.5,
    meetings: [
      { days: ['M', 'W', 'F'], start: '10:00', end: '10:50', location: 'West Hall 104', type: 'Lecture' },
    ],
  },
  {
    id: 'CMPS215-1',
    crn: '21503',
    code: 'CMPS 215',
    title: 'Computer Systems',
    instructor: 'Dr. S. K.',
    campus: 'Main Campus',
    section: '1',
    credits: 3,
    capacity: { enrolled: 20, limit: 25 },
    attributes: [],
    prerequisites: 'CMPS 201',
    restrictions: 'None',
    difficulty: 4.0,
    workload: 4.0,
    meetings: [
      { days: ['M', 'W'], start: '15:30', end: '16:45', location: 'Bechtel 211', type: 'Lecture' },
      { days: ['F'], start: '11:00', end: '12:15', location: 'Bechtel 116', type: 'Lab' },
    ],
  },
];
